version: '3.8'

services:
  mongo:
    image: mongo:8.0.3
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - app_network

  redis:
    image: redis:7.4.1
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - app_network

minio:
    image: minio/minio:latest
    container_name: minio_container
    ports:
      - "9000:9000"
      - "9001:9001" # Porta para o console do MinIO
    environment:
      MINIO_ROOT_USER: minioadmin 
      MINIO_ROOT_PASSWORD: minioadmin 
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data 
    networks:
      - app_network

volumes:
  minio_data:

networks:
  app_network:
    driver: bridge
